CREATE TABLE IF NOT EXISTS admin (
  IdAdmn INT AUTO_INCREMENT PRIMARY KEY,
  AdmnNom VARCHAR(255) NOT NULL,
  AdmnPrenom VARCHAR(255) NULL,
  UserName VARCHAR(255) NOT NULL UNIQUE,
  Mdp VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS passager (
  NumPssrt VARCHAR(20) NOT NULL PRIMARY KEY,
  PassNom VARCHAR(255) NOT NULL,
  PassPrenom VARCHAR(255) NULL,
  Naissance DATE NOT NULL,
  Ist BOOLEAN NOT NULL DEFAULT FALSE,
  Notam BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS vol (
  NumVol INT AUTO_INCREMENT PRIMARY KEY,
  Avion VARCHAR(255) NOT NULL,
  Origine VARCHAR(255) NOT NULL,
  Destination VARCHAR(255) NOT NULL,
  Decolage DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS prendre (
  NumPssrt VARCHAR(20) NOT NULL,
  NumVol INT NOT NULL,
  PRIMARY KEY (NumPssrt, NumVol),
  FOREIGN KEY (NumPssrt) REFERENCES passager(NumPssrt),
  FOREIGN KEY (NumVol) REFERENCES vol(NumVol)
);

